### ISSUE TITLE
About the collection

### ISSUE THREAD

**Issue by aitanjiujue** [MicrosoftDocs/powerapps-docs.zh-cn#2]
[在此处输入反馈]
How can I use multiple tables to generate a collection and display the data accordingly
not like this
![image](https://user-images.githubusercontent.com/46554013/62195842-66fcc100-b3af-11e9-8c13-dc9ed4b00ed1.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 59975a54-2a0b-0148-0fd1-a4ffd51c8d5a
* Version Independent ID: d3faf9fc-d312-db0b-1369-d72c3bd47fd3
* Content: [函数、信号和枚举 - PowerApps](https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/formula-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/blob/live/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by srvbpigh** [comment]
Hello, @aitanjiujue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by aitanjiujue** [comment]
hi, @srvbpigh 
thanks a lot

**Comment by CeciAc** [comment]
Hello, @aitanjiujue

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by aitanjiujue** [comment]
hi, @CeciAc 
ok   thinks
