### ISSUE TITLE
About connecting to oracle databases

### ISSUE THREAD

**Issue by aitanjiujue** [MicrosoftDocs/powerapps-docs.zh-cn#3]
Hello Microsoft team today I met some problems when connected to the oracle database, in the default environment I can connect to the database, but I can't default environment to create entities, however in my new environment to create entities but not be able to connect to the gateway, on the other hand, I don't see in your document given on this introduction, if I can't see because I don't care you write this document, then please tell me thank you very much

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7251b71d-90a2-88b6-ddb0-5ae03271f0ae
* Version Independent ID: ae948091-f13d-edaf-757f-fa6bfe2aca35
* Content: [连接到 Oracle 数据库 - PowerApps](https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/connections/connection-oracledb)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-oracledb.md](https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-oracledb.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by srvbpigh** [comment]
Hello, @aitanjiujue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @aitanjiujue

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
