### ISSUE TITLE
画布应用集成到网站和其他服务中在Firefox和Chrome中不能访问

### ISSUE THREAD

**Issue by Risin9** [MicrosoftDocs/powerapps-docs.zh-cn#5]
[在此处输入反馈]
画布应用集成到网站和其他服务中在Firefox和Chrome中不能访问
![image](https://user-images.githubusercontent.com/28332139/83367030-09793c80-a3e5-11ea-87a0-b34593568176.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 559b4613-fbe0-45dc-f8bf-ff3a70b5f66e
* Version Independent ID: 36921b82-2295-8d26-9be0-d2d23ee11ab7
* Content: [将画布应用集成到网站和其他服务中 - Power Apps](https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/embed-apps-dev)
* Content Source: [powerapps-docs/maker/canvas-apps/embed-apps-dev.md](https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/blob/live/powerapps-docs/maker/canvas-apps/embed-apps-dev.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by srvbpigh** [comment]
Hello, @Risin9
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@Risin9 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/powerapps-docs/issues/1468。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
