### ISSUE TITLE
Chinese Translation issues

### ISSUE THREAD

**Issue by GZFrankPeng** [MicrosoftDocs/powerapps-docs.zh-cn#6]
[中文自动翻译中，把Power Apps，以及Power Automate 翻译为”电源应用，电源自动化“了]
![image](https://user-images.githubusercontent.com/31057037/85121172-e52bb580-b256-11ea-8619-2db0cc529f98.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2c103d76-66ed-dcb3-4b6c-904e59143932
* Version Independent ID: fccd2495-7ac4-d2ab-dc8e-c08992a6af12
* Content: [本地数据网关 - Power Apps](https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/gateway-reference#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/gateway-reference.md](https://github.com/MicrosoftDocs/powerapps-docs.zh-cn/blob/live/powerapps-docs/maker/canvas-apps/gateway-reference.md)
* Service: **powerapps**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by srvbpigh** [comment]
你好，@GZFrankPeng，

我们正在改进我们的内部流程和工程管道。遗憾的是，这会导致我们延迟处理你的反馈。

非常感谢你为我们的文章贡献内容，我们期待继续获取你的支持和理解。

**Comment by jowilco** [comment]
Fixed as "这些云服务包括 Power BI、Power Apps、Power Automate、Azure Analysis Services 和 Azure 逻辑应用。"
